-- 코드를 작성해주세요

# select ID, FISH_NAME, LENGTH from FISH_INFO 
SELECT f.ID, n.FISH_NAME, f.LENGTH
FROM FISH_INFO f
JOIN FISH_NAME_INFO n ON f.FISH_TYPE = n.FISH_TYPE
JOIN (
    SELECT FISH_TYPE, MAX(LENGTH) AS MAX_LEN
    FROM FISH_INFO
    GROUP BY FISH_TYPE
) AS m ON f.FISH_TYPE = m.FISH_TYPE AND f.LENGTH = m.MAX_LEN order by ID;