-- 코드를 입력하세요
# SELECT COUNT(INGREDIENT_TYPE) 
# SELECT SUM(TOTAL_ORDER)
# SELECT  F.FLAVOR, F.TOTAL_ORDER, I.INGREDIENT_TYPE
SELECT INGREDIENT_TYPE, SUM(TOTAL_ORDER)
# SELECT *
FROM FIRST_HALF AS F
JOIN ICECREAM_INFO AS I ON F.FLAVOR = I.FLAVOR
GROUP BY INGREDIENT_TYPE
# HAVING 
ORDER BY SHIPMENT_ID
